### ISSUE TITLE
Unrendered emoji codes - update

### ISSUE THREAD

**Issue by lukaszApilo** [siosio/EmojiCommitLogViewer#5]
Same as #2 - Observed unrendered emoji codes:
- :technologist:  `:technologist:`
- :necktie:  `:necktie:`
- :bricks:  `:bricks:`

Perhaps more : see [Gitmoji](https://gitmoji.carloscuesta.me/) for more info.

**Comment by siosio** [comment]
We've responded! Please use 1.0.7.
